### ISSUE TITLE
Years don't roll over correctly after December

### ISSUE THREAD

**Issue by coraunderhill** [dance2die/calendar-dates#26] opened 2018-12-06 23:37 UTC
## Steps to reproduce
Create a new `Date` using December 2018 as your target.

## Expected  behavior
After December 31st is reached, the calendar should roll over into January of 2019

## Actual behavior
The calendar continues the month count into 2018-13 instead of 2019-01 as expected

![example](https://user-images.githubusercontent.com/868416/49618311-f6f78180-f96c-11e8-843e-cbdeb0307431.png)

## Environment data
`npm --version`: 6.4.1

**Comment by coraunderhill** [comment] 2018-12-06 23:39
![Exampe](https://user-images.githubusercontent.com/868416/49618311-f6f78180-f96c-11e8-843e-cbdeb0307431.png)

**Comment by dance2die** [comment] 2018-12-07 02:52
@coraunderhill Oh yikes 😲.
Thank you for the report

I will fix it~

**Comment by dance2die** [comment] 2018-12-07 02:58
It seems like the problem also occurs for January as well, where ISO month is set to 0, not 1

**Comment by dance2die** [comment] 2018-12-07 03:10
Thank you, @coraunderhill.
The issue is fixed in [version 2.4.4](https://www.npmjs.com/package/calendar-dates/v/2.4.4)
(and added the test as well).

**Closed by dance2die** 2018-12-07 03:10 UTC
